language: node_js
node_js: stable
cache:
  apt: true
  directories:
  - node_modules
install:
- npm install
script:
- hexo g
after_script:
- cd ./public
- git init
- git config user.name "gethin.yan"
- git config user.email "gethin.yan@gmail.com"
- git add .
- git commit -m "update notes"
- git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:master
branches:
  only:
  - master
env:
  global:
  - GH_REF: github.com/gethinyan/gethinyan.github.io.git
before_install:
- openssl aes-256-cbc -K $encrypted_99fb0ffd7f47_key -iv $encrypted_99fb0ffd7f47_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
after_success:
- ssh root@47.52.175.26 "./auto_deploy.sh"
