language: node_js

node_js: stable

cache:
  apt: true
  directories:
    - node_modules

install:
  - npm install

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "gethin.yan"
  - git config user.email "gethin.yan@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - master

env:
  global:
    - GH_REF: github.com/gethinyan/gethinyan.github.io.git
