branches:
  only:
  - master
language: node_js
node_js: stable
cache:
  apt: true
  directories:
    - node_modules
install:
- npm install
script:
- hexo clean
- hexo g
after_script:
- cd ./public
- git init
- git config user.name "gethin.yan"
- git config user.email "gethin.yan@gmail.com"
- git add .
- git commit -m "update notes"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
env:
  global:
  - GH_REF: github.com/gethinyan/notes.git
